#ifndef SOFTNOTE_CHAINPARAMSSEEDS_H
#define SOFTNOTE_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the softnote network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x7f,0x00,0x00,0x01,0x44,0xc5,
};

static const uint8_t chainparams_seed_test[] = {
    0x01,0x04,0x7f,0x00,0x00,0x01,0x44,0xc0,
};
#endif // SOFTNOTE_CHAINPARAMSSEEDS_H

